### ISSUE TITLE
wich GPOI pin is used in the irrigation.bin ?

### ISSUE THREAD

**Issue by v0r73x** [HomeKidd/ESP8266-HomeKit-Irrigation-System-Eve-Aqua#1]
Hi Mate,

So nice what you invented here :) i like it so much that you calculate the water flow as well.

But one big open thing - which GPIO Pins are used for that ? Since its inpossible to review your code i would like to know which pin is in use whitout measureing all of them ;) 
Will be n1ce if you can tell me on a esp8266 which port must be used for magnet valve to trigger 

br from Berlin 
v0r73x

**Comment by HomeKidd** [comment]
Hi!
Thanks!
The pinout is exactly the same as the [Sonoff Basic](http://s.click.aliexpress.com/e/d07wkNS) so you can find everything, the pinout, LED logic etc ✌️
